Repository jskomal/rancid-tomatillos, pull requests merged in 2022-03, with the labels that each got.

#1 Iteration0/main view Closes #2 Closes #3
  docs/pull_request_template.md
  src/App/App.css
  src/App/App.js
  src/Card/Card.css
  src/Card/Card.js
  src/Header/Header.css
  src/Header/Header.js
  src/Main/Main.css
  src/Main/Main.js
  src/index.css
  src/movieData.js
Labels: iteration 1

#14 Feature/iteration2/single movie view - Closes #4, #5, #6
  src/App/App.js
  src/Card/Card.js
  src/Header/Header.js
  src/Main/Main.js
  src/SingleView/SingleView.css
  src/SingleView/SingleView.js
  src/movieData.js
Labels: iteration 2

#15 Feature/api calls
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  src/APICalls.js
  src/App/App.js
  src/Card/Card.js
  src/Main/Main.js
  src/SingleView/SingleView.css
  src/SingleView/SingleView.js
  src/movieData.js
Labels: iteration 3
